# Generated by Django 6.0.6 on 2026-07-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_location_alert_location_batch_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
